# Setup
title: ChemData
description: To share my learning journey.
url: 
avatar: /avatar1.jpg
paginate: 5
permalink: pretty
cover_image: /bg1.jpg
#<a href='https://www.freepik.com/vectors/background'>Background vector created by starline - www.freepik.com</a>
# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: 
  card: summary
logo: logo.png
social:
  name: 
  links:
    - 
    - 
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Brenda Ferrari
  url: 
  github: https://github.com/brendaferrari
  